sample_app/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root	'static_pages#home'

  get		'/help',		to: 'static_pages#help'

  get		'/about',		to: 'static_pages#about'

  get		'/contact',		to: 'static_pages#contact'
  
  get		'/signup',		to: 'users#new'
  
  post		'/signup',		to: 'users#create'
  
  get		'login',		to: 'sessions#new'
  
  post		'/login',		to: 'sessions#create'
  
  delete	'/logout',		to: 'sessions#destroy'
  
  resources			:users
end

sample_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

sample_app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
  
  def contact
  end
end

sample_app/app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
		base_title = "Ruby on Rails Tutorial Sample App"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end
end

sample_app/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

sample_app/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    the <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",		about_path		%></li>
      <li><%= link_to "Contact",	contact_path	%></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

sample_app/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<!--top logo button-->
		<%= link_to "sample.app", root_path, id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<!--home link button-->
				<li><%= link_to "Home",		root_path	%></li>
				<!--help link button-->
				<li><%= link_to "Help",		help_path	%></li>
				<% if logged_in? %>
					<!--users link button-->
					<li><%= link_to "Users", users_path %></li>
					<!--create dropdown view-->
					<li class= "dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							Account<b class="caret"></b>
						</a>
						<!--setting dropdown contents-->
						<ul class="dropdown-menu">
							<!--profile link button-->
							<li><%= link_to "Profile", current_user %></li>
							<!--setting link button-->
							<li><%= link_to "Settings", 'edit_user_path(current_user)' %></li>
							<li class="divider"></li>
							<!--logout link button-->
							<li><%= link_to "Log out", logout_path, method: :delete %></li>
						</ul>
					</li>
				<% else %>
					<!--login link button-->
					<li><%= link_to "Log in", login_path %></li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

sample_app/app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

sample_app/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

sample_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= render 'layouts/rails_default' %>
		<%= render 'layouts/shim' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |message_type, message| %>
				<%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
			<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>

sample_app/app/views/shared/_error_messages.html.erb
<!--check errors-->
<% if @user.errors.any? %>
	<div id="error_explanation">
		<!--show error alert-->
		<div class="alert alert-danger">
			The form contains <%= pluralize(@user.errors.count, "error") %>.
		</div>
		<!--show error meeages-->
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %> </li>
			<% end %>
		</ul>
	</div>
<% end %>

sample_app/app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<h1>About</h1>
<p>
  <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
  is a <a href="https://railstutorial.jp/#ebook">book</a> and
  <a href="https://railstutorial.jp/#screencast">screencast</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

sample_app/app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="https://railstutorial.jp/contact">contact page</a>.
</p>

sample_app/app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<!DOCTYPE html>
<h1>Help</h1>
<p>  Get help on the Ruby on Rails Tutorial at the
  <a href="https://railstutorial.jp/help">Rails Tutorial help
  page</a>.
  To get help on this sample app, see the
  <a href="https://railstutorial.jp/#ebook">
  <em>Ruby on Rails Tutorial</em> book</a>.
</p>

sample_app/app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>
  <h2>
    This is the home page for the
    <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>
  
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("rails.png", alt: "Rails logo"), 'http://rubyonrails.org/' %>
<!--<%= image_tag("kitten.jpg", alt: "kitten") %>-->

sample_app/app/views/users/_user.html.erb
<li>
	<!--icon-->
	<%= gravatar_for user, size: 50 %>
	<!--user link-->
	<%= link_to user.name, user %>
	<!--delete link-->
	<% if current_user.admin? && !current_user?(user) %>
		| <%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" } %>
	<% end %>
</li>

sample_app/app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user) do |f| %>
			<!--error message-->
			<%= render 'shared/error_messages' %>
			
			<!--name form-->
			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>
			
			<!--email form-->
			<%= f.label :email %>
			<%= f.email_field :email, class: 'form-control' %>
			
			<!--password form-->
			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>
			
			<!--confirmaiton form-->
			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>
			
			<!--save button-->
			<%= f.submit "Save changes", class: "btn btn-primaty" %>
		<% end %>
		<!--change picture form-->
		<div class="gravatar_edit">
			<%= gravatar_for @user %>
			<a href="http://gravatar.com/emails" target="_blank">change</a>
		</div>
	</div>
</div>

sample_app/app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>
<ul class="users">
	
	<%= render @users %>
	
</ul>
<%= will_paginate %>

sample_app/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user, url: signup_path) do |f| %>
			<%= render 'shared/error_messages' %>
			
			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>
			
			<%= f.label :email %>
			<%= f.email_field :email, class: 'form-control' %>
			
			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>
			
			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>
			
			<%= f.submit "Create my account", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

sample_app/app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="col-md-4">
		<section class="user_info">
			<h1>
				<%= gravatar_for @user, size:50 %>
				<%= @user.name %>
			</h1>
		</section>
	</aside>
</div>